import React from 'react'; // Import React if you haven't already
import { Af, Al, Dz, As, Ad, Ao, Ai, Ag, Ar, Am, Aw, Au, At, Az, Bs, Bh, Bd, Bb, By, Be, Bz, Bj, Bm, Bt, Bo, Ba, Bw, Br, Io, Bg, Bf, Bi, Kh, Cm, Ca, Cv, Ky, Cf, Td, Cl, Cn, Co, Km, Cg, Cd, Ck, Cr, Ci, Hr, Cu, Cw, Cy, Cz, Dk, Dj, Dm, Do, Ec, Eg, Sv, Gq, Er, Ee, Et, Fk, Fo, Fj, Fi, Fr, Pf, Ga, Gm, Ge, De, Gh, Gi, Gr, Gl, Gd, Gu, Gt, Gg, Gn, Gw, Ht, Hn, Hk, Hu, Is, In, Id, Ir, Iq, Ie, Im, Il, It, Jm, Jp, Je, Jo, Kz, Ke, Ki, Kp, Kr, Kw, Kg, La, Lv, Lb, Ls, Lr, Ly, Li, Lt, Lu, Mo, Mk, Mg, Mw, My, Mv, Ml, Mt, Mh, Mq, Mr, Mu, Mx, Fm, Md, Mc, Mn, Me, Ms, Ma, Mz, Mm, Na, Nr, Np, Nl, Nz, Ni, Ne, Ng, Nu, Nf, Mp, No, Om, Pk, Pw, Ps, Pa, Pg, Py, Pe, Ph, Pn, Pl, Pt, Pr, Qa, Ro, Ru, Rw, Kn, Lc, Ws, Sm, St, Sa, Sn, Rs, Sc, Sl, Sg, Sx, Sk, Si, Sb, So, Za, Ss, Es, Lk, Sd, Sr, Sz, Se, Ch, Sy, Tw, Tj, Tz, Th, Tg, Tk, To, Tt, Tn, Tr, Tm, Tc, Tv, Ug, Ua, Ae, Gb, Us, Uy, Uz, Vu, Ve, Vn, Vi, Ye, Zm, Zw } from "react-flags-select";


// List of countries with their codes
var countries = [
    {code: Af, countryName: "Afghanistan", language: "Pashto"},
    {code: Al, countryName: "Albania", language: "Albanian"},
    {code: Dz, countryName: "Algeria", language: "Arabic"},
    {code: As, countryName: "American Samoa", language: "Samoan"},
    {code: Ad, countryName: "Andorra", language: "Catalan"},
    {code: Ao, countryName: "Angola", language: "Portuguese"},
    {code: Ai, countryName: "Anguilla", language: "English"},
    {code: Ag, countryName: "Antigua and Barbuda", language: "English"},
    {code: Ar, countryName: "Argentina", language: "Spanish"},
    {code: Am, countryName: "Armenia", language: "Armenian"},
    {code: Aw, countryName: "Aruba", language: "Dutch"},
    {code: Au, countryName: "Australia", language: "English"},
    {code: At, countryName: "Austria", language: "German"},
    {code: Az, countryName: "Azerbaijan", language: "Azerbaijani"},
    {code: Bs, countryName: "Bahamas", language: "English"},
    {code: Bh, countryName: "Bahrain", language: "Arabic"},
    {code: Bd, countryName: "Bangladesh", language: "Bengali"},
    {code: Bb, countryName: "Barbados", language: "English"},
    {code: By, countryName: "Belarus", language: "Belarusian"},
    {code: Be, countryName: "Belgium", language: "French"},
    {code: Bz, countryName: "Belize", language: "English"},
    {code: Bj, countryName: "Benin", language: "French"},
    {code: Bm, countryName: "Bermuda", language: "English"},
    {code: Bt, countryName: "Bhutan", language: "Dzongkha"},
    {code: Bo, countryName: "Bolivia, Plurinational State of", language: "Spanish"},
    {code: Ba, countryName: "Bosnia and Herzegovina", language: "Bosnian"},
    {code: Bw, countryName: "Botswana", language: "Setswana"},
    {code: Br, countryName: "Brazil", language: "Portuguese"},
    {code: Io, countryName: "British Indian Ocean Territory", language: "English"},
    {code: Bg, countryName: "Bulgaria", language: "Bulgarian"},
    {code: Bf, countryName: "Burkina Faso", language: "French"},
    {code: Bi, countryName: "Burundi", language: "Kirundi"},
    {code: Km, countryName: "Comoros", language: "Comorian"},
    {code: Cg, countryName: "Congo", language: "French"},
    {code: Cd, countryName: "Democratic Republic of the Congo", language: "French"},
    {code: Cr, countryName: "Costa Rica", language: "Spanish"},
    {code: Ci, countryName: "Côte d'Ivoire", language: "French"},
    {code: Hr, countryName: "Croatia", language: "Croatian"},
    {code: Cu, countryName: "Cuba", language: "Spanish"},
    {code: Cw, countryName: "Curaçao", language: "Dutch"},
    {code: Cy, countryName: "Cyprus", language: "Greek"},
    {code: Cz, countryName: "Czech Republic", language: "Czech"},
    {code: Dk, countryName: "Denmark", language: "Danish"},
    {code: Dj, countryName: "Djibouti", language: "French"},
    {code: Dm, countryName: "Dominica", language: "English"},
    {code: Do, countryName: "Dominican Republic", language: "Spanish"},
    {code: Ec, countryName: "Ecuador", language: "Spanish"},
    {code: Eg, countryName: "Egypt", language: "Arabic"},
    {code: Sv, countryName: "El Salvador", language: "Spanish"},
    {code: Gq, countryName: "Equatorial Guinea", language: "Spanish"},
    {code: Er, countryName: "Eritrea", language: "Tigrinya"},
    {code: Ee, countryName: "Estonia", language: "Estonian"},
    {code: Et, countryName: "Ethiopia", language: "Amharic"},
    {code: Fk, countryName: "Falkland Islands (Malvinas)", language: "English"},
    {code: Fo, countryName: "Faroe Islands", language: "Faroese"},
    {code: Fj, countryName: "Fiji", language: "Fijian"},
    {code: Fi, countryName: "Finland", language: "Finnish"},
    {code: Fr, countryName: "France", language: "French"},
    {code: Pf, countryName: "French Polynesia", language: "French"},
    {code: Ga, countryName: "Gabon", language: "French"},
    {code: Gm, countryName: "Gambia", language: "English"},
    {code: Ge, countryName: "Georgia", language: "Georgian"},
    {code: De, countryName: "Germany", language: "German"},
    {code: Gh, countryName: "Ghana", language: "English"},
    {code: Gi, countryName: "Gibraltar", language: "English"},
    {code: Gr, countryName: "Greece", language: "Greek"},
    {code: Gl, countryName: "Greenland", language: "Greenlandic"},
    {code: Gd, countryName: "Grenada", language: "English"},
    {code: Gu, countryName: "Guam", language: "English and Chamorro"},
    {code: Gt, countryName: "Guatemala", language: "Spanish"},
    {code: Gg, countryName: "Guernsey", language: "English"},
    {code: Gn, countryName: "Guinea", language: "French"},
    {code: Gw, countryName: "Guinea-Bissau", language: "Portuguese"},
    {code: Ht, countryName: "Haiti", language: "Haitian Creole and French"},
    {code: Hn, countryName: "Honduras", language: "Spanish"},
    {code: Hk, countryName: "Hong Kong", language: "Chinese"},
    {code: Hu, countryName: "Hungary", language: "Hungarian"},
    {code: Is, countryName: "Iceland", language: "Icelandic"},
    {code: In, countryName: "India", language: "Hindi"},
    {code: Id, countryName: "Indonesia", language: "Indonesian"},
    {code: Ir, countryName: "Iran, Islamic Republic of", language: "Persian"},
    {code: Iq, countryName: "Iraq", language: "Arabic"},
    {code: Ie, countryName: "Ireland", language: "Irish"},
    {code: Im, countryName: "Isle of Man", language: "English"},
    {code: Il, countryName: "Israel", language: "Hebrew"},
    {code: It, countryName: "Italy", language: "Italian"},
    {code: Jm, countryName: "Jamaica", language: "English"},
    {code: Jp, countryName: "Japan", language: "Japanese"},
    {code: Je, countryName: "Jersey", language: "English"},
    {code: Jo, countryName: "Jordan", language: "Arabic"},
    {code: Kz, countryName: "Kazakhstan", language: "Kazakh"},
    {code: Ke, countryName: "Kenya", language: "Swahili"},
    {code: Ki, countryName: "Kiribati", language: "English"},
    {code: Kp, countryName: "North Korea", language: "Korean"},
    {code: Kr, countryName: "South Korea", language: "Korean"},
    {code: Kw, countryName: "Kuwait", language: "Arabic"},
    {code: Kg, countryName: "Kyrgyzstan", language: "Kyrgyz"},
    {code: La, countryName: "Lao People's Democratic Republic", language: "Lao"},
    {code: Lv, countryName: "Latvia", language: "Latvian"},
    {code: Lb, countryName: "Lebanon", language: "Arabic"},
    {code: Ls, countryName: "Lesotho", language: "Sesotho"},
    {code: Lr, countryName: "Liberia", language: "English"},
    {code: Ly, countryName: "Libya", language: "Arabic"},
    {code: Li, countryName: "Liechtenstein", language: "German"},
    {code: Lt, countryName: "Lithuania", language: "Lithuanian"},
    {code: Lu, countryName: "Luxembourg", language: "Luxembourgish"},
    {code: Mo, countryName: "Macao", language: "Chinese"},
    {code: Mk, countryName: "Republic of Macedonia", language: "Macedonian"},
    {code: Mg, countryName: "Madagascar", language: "Malagasy"},
    {code: Mw, countryName: "Malawi", language: "Chichewa"},
    {code: My, countryName: "Malaysia", language: "Malay"},
    {code: Mv, countryName: "Maldives", language: "Dhivehi"},
    {code: Ml, countryName: "Mali", language: "French"},
    {code: Mt, countryName: "Malta", language: "Maltese"},
    {code: Mh, countryName: "Marshall Islands", language: "Marshallese"},
    {code: Mq, countryName: "Martinique", language: "French"},
    {code: Mr, countryName: "Mauritania", language: "Arabic"},
    {code: Mu, countryName: "Mauritius", language: "English"},
    {code: Mx, countryName: "Mexico", language: "Spanish"},
    {code: Fm, countryName: "Micronesia, Federated States of", language: "English"},
    {code: Md, countryName: "Republic of Moldova", language: "Moldovan"},
    {code: Mc, countryName: "Monaco", language: "French"},
    {code: Mn, countryName: "Mongolia", language: "Mongolian"},
    {code: Me, countryName: "Montenegro", language: "Montenegrin"},
    {code: Ms, countryName: "Montserrat", language: "English"},
    {code: Ma, countryName: "Morocco", language: "Arabic"},
    {code: Mz, countryName: "Mozambique", language: "Portuguese"},
    {code: Mm, countryName: "Myanmar", language: "Burmese"},
    {code: Na, countryName: "Namibia", language: "English"},
    {code: Nr, countryName: "Nauru", language: "Nauruan"},
    {code: Np, countryName: "Nepal", language: "Nepali"},
    {code: Nl, countryName: "Netherlands", language: "Dutch"},
    {code: Nz, countryName: "New Zealand", language: "English"},
    {code: Ni, countryName: "Nicaragua", language: "Spanish"},
    {code: Ne, countryName: "Niger", language: "French"},
    {code: Ng, countryName: "Nigeria", language: "English"},
    {code: Nu, countryName: "Niue", language: "Niuean and English"},
    {code: Nf, countryName: "Norfolk Island", language: "English"},
    {code: Mp, countryName: "Northern Mariana Islands", language: "English and Chamorro"},
    {code: No, countryName: "Norway", language: "Norwegian"},
    {code: Om, countryName: "Oman", language: "Arabic"},
    {code: Pk, countryName: "Pakistan", language: "Urdu"},
    {code: Pw, countryName: "Palau", language: "Palauan and English"},
    {code: Ps, countryName: "Palestine, State of", language: "Arabic"},
    {code: Pa, countryName: "Panama", language: "Spanish"},
    {code: Pg, countryName: "Papua New Guinea", language: "English"},
    {code: Py, countryName: "Paraguay", language: "Spanish"},
    {code: Pe, countryName: "Peru", language: "Spanish"},
    {code: Ph, countryName: "Philippines", language: "Filipino"},
    {code: Pn, countryName: "Pitcairn", language: "English"},
    {code: Pl, countryName: "Poland", language: "Polish"},
    {code: Pt, countryName: "Portugal", language: "Portuguese"},
    {code: Pr, countryName: "Puerto Rico", language: "Spanish"},
    {code: Qa, countryName: "Qatar", language: "Arabic"},
    {code: Ro, countryName: "Romania", language: "Romanian"},
    {code: Ru, countryName: "Russia", language: "Russian"},
    {code: Rw, countryName: "Rwanda", language: "Kinyarwanda"},
    {code: Kn, countryName: "Saint Kitts and Nevis", language: "English"},
    {code: Lc, countryName: "Saint Lucia", language: "English"},
    {code: Ws, countryName: "Samoa", language: "Samoan"},
    {code: Sm, countryName: "San Marino", language: "Italian"},
    {code: St, countryName: "Sao Tome and Principe", language: "Portuguese"},
    {code: Sa, countryName: "Saudi Arabia", language: "Arabic"},
    {code: Sn, countryName: "Senegal", language: "French"},
    {code: Rs, countryName: "Serbia", language: "Serbian"},
    {code: Sc, countryName: "Seychelles", language: "English"},
    {code: Sl, countryName: "Sierra Leone", language: "English"},
    {code: Sg, countryName: "Singapore", language: "English, Malay, Mandarin, Tamil"},
    {code: Sx, countryName: "Sint Maarten (Dutch part)", language: "Dutch"},
    {code: Sk, countryName: "Slovakia", language: "Slovak"},
    {code: Si, countryName: "Slovenia", language: "Slovene"},
    {code: Sb, countryName: "Solomon Islands", language: "English"},
    {code: So, countryName: "Somalia", language: "Somali"},
    {code: Za, countryName: "South Africa", language: "Zulu"},
    {code: Ss, countryName: "South Sudan", language: "English"},
    {code: Es, countryName: "Spain", language: "Spanish"},
    {code: Lk, countryName: "Sri Lanka", language: "Sinhala"},
    {code: Sd, countryName: "Sudan", language: "Arabic and English"},
    {code: Sr, countryName: "Suriname", language: "Dutch"},
    {code: Sz, countryName: "Swaziland", language: "Swati"},
    {code: Se, countryName: "Sweden", language: "Swedish"},
    {code: Ch, countryName: "Switzerland", language: "German, French, Italian, and Romansh"},
    {code: Sy, countryName: "Syrian Arab Republic", language: "Arabic"},
    {code: Tw, countryName: "Taiwan", language: "Chinese"},
    {code: Tj, countryName: "Tajikistan", language: "Tajik"},
    {code: Tz, countryName: "Tanzania, United Republic of", language: "Swahili"},
    {code: Th, countryName: "Thailand", language: "Thai"},
    {code: Tg, countryName: "Togo", language: "French"},
    {code: Tk, countryName: "Tokelau", language: "Tokelauan and English"},
    {code: To, countryName: "Tonga", language: "Tongan"},
    {code: Tt, countryName: "Trinidad and Tobago", language: "English"},
    {code: Tn, countryName: "Tunisia", language: "Arabic"},
    {code: Tr, countryName: "Turkey", language: "Turkish"},
    {code: Tm, countryName: "Turkmenistan", language: "Turkmen"},
    {code: Tc, countryName: "Turks and Caicos Islands", language: "English"},
    {code: Tv, countryName: "Tuvalu", language: "Tuvaluan"},
    {code: Ua, countryName: "Ukraine", language: "Ukrainian"},
    {code: Ae, countryName: "United Arab Emirates", language: "Arabic"},
    {code: Gb, countryName: "United Kingdom", language: "English"},
    {code: Us, countryName: "United States", language: "English"},
    {code: Uy, countryName: "Uruguay", language: "Spanish"},
    {code: Uz, countryName: "Uzbekistan", language: "Uzbek"},
    {code: Vu, countryName: "Vanuatu", language: "Bislama"},
    {code: Ve, countryName: "Venezuela, Bolivarian Republic of", language: "Spanish"},
    {code: Vn, countryName: "Viet Nam", language: "Vietnamese"},
    {code: Vi, countryName: "Virgin Islands, U.S.", language: "English"},
    {code: Ye, countryName: "Yemen", language: "Arabic"},
    {code: Zm, countryName: "Zambia", language: "English"},
    {code: Zw, countryName: "Zimbabwe", language: "English"}
];

const formatCountryCode = (code) => {
    return code.charAt(0).toUpperCase() + code.charAt(1).toLowerCase();
};


// Initialize an empty list to store country objects
const countriesList = [];

// Loop through each country in the countries object

    // const formattedCountryCode = formatCountryCode(value.code);
countries.forEach(function(country) {
    let FlagComponent = country.code;

    countriesList.push({
        language: country.language,
        countryName: country.countryName,
        code: <FlagComponent />,
    });
});

export default countriesList;
